apiVersion: v1
kind: Service
metadata:
  labels:
    control-plane: centurion
  name: centurion-metrics-service
  namespace: centurion
spec:
  ports:
  - name: https
    port: 8443
    targetPort: https
  selector:
    control-plane: centurion
