apiVersion: v1
kind: Service
metadata:
  labels:
    control-plane: snf
  name: snf-metrics-service
  namespace: snf
spec:
  ports:
  - name: https
    port: 8443
    targetPort: https
  selector:
    control-plane: snf
