# permissions for end users to edit eventlisteners.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: snf-eventlistener-editor-role
rules:
- apiGroups:
  - snf.ccs.sniff-n-fix.com
  resources:
  - eventlisteners
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - snf.ccs.sniff-n-fix.com
  resources:
  - eventlisteners/status
  verbs:
  - get
