# permissions for end users to view eventlisteners.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: snf-eventlistener-viewer-role
rules:
- apiGroups:
  - snf.ccs.sniff-n-fix.com
  resources:
  - eventlisteners
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - snf.ccs.sniff-n-fix.com
  resources:
  - eventlisteners/status
  verbs:
  - get
