
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  creationTimestamp: null
  name: snf-role
rules:
- apiGroups:
  - ""
  resources:
  - pods
  verbs:
  - delete
- apiGroups:
  - snf.ccs.sniff-n-fix.com
  resources:
  - eventlisteners
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - snf.ccs.sniff-n-fix.com
  resources:
  - eventlisteners/finalizers
  verbs:
  - update
- apiGroups:
  - snf.ccs.sniff-n-fix.com
  resources:
  - eventlisteners/status
  verbs:
  - get
  - patch
  - update
